# Generated by Django 5.1.6 on 2025-03-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiwiti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
